export const BASE_URL = GLOBAL_TGCW_CONFIG?.BASE_URL || process.env.TGCW_BASE_URL;
export const AUTH_DOMAIN = GLOBAL_TGCW_CONFIG?.AUTH_DOMAIN || process.env.TGCW_AUTH_DOMAIN;
export const AUTH_CLIENT_ID = GLOBAL_TGCW_CONFIG?.AUTH_CLIENT_ID || process.env.TGCW_AUTH_CLIENT_ID;
